-- Create "banks" table
CREATE TABLE "public"."banks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "country" character varying NOT NULL,
  "website" character varying NULL,
  "logo_url" character varying NULL,
  PRIMARY KEY ("id")
);
-- Create "bank_translations" table
CREATE TABLE "public"."bank_translations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "locale" character varying NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NOT NULL,
  "bank_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "bank_translations_banks_translations" FOREIGN KEY ("bank_id") REFERENCES "public"."banks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "currency_rates" table
CREATE TABLE "public"."currency_rates" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "currency" character varying NOT NULL,
  "buy" double precision NULL,
  "sell" double precision NULL,
  "bank_currency_rates" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "currency_rates_banks_currency_rates" FOREIGN KEY ("bank_currency_rates") REFERENCES "public"."banks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "offers" table
CREATE TABLE "public"."offers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "type" character varying NOT NULL,
  "description" character varying NOT NULL,
  "link" character varying NOT NULL,
  "bank_offers" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "offers_banks_offers" FOREIGN KEY ("bank_offers") REFERENCES "public"."banks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
