// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ImportCurrencyRateInput struct {
	Base      string     `json:"base"`
	Currency  string     `json:"currency"`
	Buy       *float64   `json:"buy,omitempty"`
	Sell      *float64   `json:"sell,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}
